import './globals.css'
import FontStore from '@/store/fontStore'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${FontStore.getState().poppins} bg-[#181818]`}>{children}</body>
    </html>
  )
}
